// Real ITU calling-code + national-number-length dataset, as supplied by the
// user (the well-known `country-telephone-data` shape: code/label/phone,
// plus per-country phoneLength — a single number, an array of valid
// alternative lengths, or a min/max range). Used to build a real
// flag+country+dial-code selector (packages/ui-web's CountryCodeSelect,
// packages/ui-native's CountryCodeField) and to cap how many digits a phone
// input accepts for the selected country. `dialCode` keeps the source
// formatting verbatim (some NANP entries are dash-qualified, e.g. "1-268")
// — callers normalize to digits-only when composing a stored phone string.
//
// `maxPhoneDigits` is the largest valid national-number length for that
// country (the max of an array, or the range's max) — used purely as a
// typing cap, not full validation. Left undefined where the source gave no
// length at all (e.g. Japan) — no cap rather than a guessed one.
export interface Country {
  name: string;
  dialCode: string;
  iso2: string;
  maxPhoneDigits?: number;
}

export const COUNTRIES: Country[] = [
  { name: 'Andorra', dialCode: '376', iso2: 'AD', maxPhoneDigits: 6 },
  { name: 'United Arab Emirates', dialCode: '971', iso2: 'AE', maxPhoneDigits: 9 },
  { name: 'Afghanistan', dialCode: '93', iso2: 'AF', maxPhoneDigits: 9 },
  { name: 'Antigua and Barbuda', dialCode: '1-268', iso2: 'AG', maxPhoneDigits: 10 },
  { name: 'Anguilla', dialCode: '1-264', iso2: 'AI', maxPhoneDigits: 10 },
  { name: 'Albania', dialCode: '355', iso2: 'AL', maxPhoneDigits: 9 },
  { name: 'Armenia', dialCode: '374', iso2: 'AM', maxPhoneDigits: 6 },
  { name: 'Angola', dialCode: '244', iso2: 'AO', maxPhoneDigits: 9 },
  { name: 'Antarctica', dialCode: '672', iso2: 'AQ', maxPhoneDigits: 6 },
  { name: 'Argentina', dialCode: '54', iso2: 'AR', maxPhoneDigits: 8 },
  { name: 'American Samoa', dialCode: '1-684', iso2: 'AS', maxPhoneDigits: 10 },
  { name: 'Austria', dialCode: '43', iso2: 'AT', maxPhoneDigits: 11 },
  { name: 'Australia', dialCode: '61', iso2: 'AU', maxPhoneDigits: 9 },
  { name: 'Aruba', dialCode: '297', iso2: 'AW', maxPhoneDigits: 7 },
  { name: 'Alland Islands', dialCode: '358', iso2: 'AX', maxPhoneDigits: 10 },
  { name: 'Azerbaijan', dialCode: '994', iso2: 'AZ', maxPhoneDigits: 9 },
  { name: 'Bosnia and Herzegovina', dialCode: '387', iso2: 'BA', maxPhoneDigits: 8 },
  { name: 'Barbados', dialCode: '1-246', iso2: 'BB', maxPhoneDigits: 10 },
  { name: 'Bangladesh', dialCode: '880', iso2: 'BD', maxPhoneDigits: 10 },
  { name: 'Belgium', dialCode: '32', iso2: 'BE', maxPhoneDigits: 9 },
  { name: 'Burkina Faso', dialCode: '226', iso2: 'BF', maxPhoneDigits: 8 },
  { name: 'Bulgaria', dialCode: '359', iso2: 'BG', maxPhoneDigits: 9 },
  { name: 'Bahrain', dialCode: '973', iso2: 'BH', maxPhoneDigits: 8 },
  { name: 'Burundi', dialCode: '257', iso2: 'BI', maxPhoneDigits: 8 },
  { name: 'Benin', dialCode: '229', iso2: 'BJ', maxPhoneDigits: 8 },
  { name: 'Saint Barthelemy', dialCode: '590', iso2: 'BL', maxPhoneDigits: 9 },
  { name: 'Bermuda', dialCode: '1-441', iso2: 'BM', maxPhoneDigits: 10 },
  { name: 'Brunei Darussalam', dialCode: '673', iso2: 'BN', maxPhoneDigits: 7 },
  { name: 'Bolivia', dialCode: '591', iso2: 'BO', maxPhoneDigits: 9 },
  { name: 'Brazil', dialCode: '55', iso2: 'BR', maxPhoneDigits: 11 },
  { name: 'Bahamas', dialCode: '1-242', iso2: 'BS', maxPhoneDigits: 10 },
  { name: 'Bhutan', dialCode: '975', iso2: 'BT', maxPhoneDigits: 7 },
  { name: 'Bouvet Island', dialCode: '47', iso2: 'BV', maxPhoneDigits: 10 },
  { name: 'Botswana', dialCode: '267', iso2: 'BW', maxPhoneDigits: 7 },
  { name: 'Belarus', dialCode: '375', iso2: 'BY', maxPhoneDigits: 9 },
  { name: 'Belize', dialCode: '501', iso2: 'BZ', maxPhoneDigits: 7 },
  { name: 'Canada', dialCode: '1', iso2: 'CA', maxPhoneDigits: 10 },
  { name: 'Cocos (Keeling) Islands', dialCode: '61', iso2: 'CC', maxPhoneDigits: 10 },
  { name: 'Congo, Democratic Republic of the', dialCode: '243', iso2: 'CD', maxPhoneDigits: 7 },
  { name: 'Central African Republic', dialCode: '236', iso2: 'CF', maxPhoneDigits: 8 },
  { name: 'Congo, Republic of the', dialCode: '242', iso2: 'CG', maxPhoneDigits: 9 },
  { name: 'Switzerland', dialCode: '41', iso2: 'CH', maxPhoneDigits: 9 },
  { name: "Cote d'Ivoire", dialCode: '225', iso2: 'CI', maxPhoneDigits: 8 },
  { name: 'Cook Islands', dialCode: '682', iso2: 'CK', maxPhoneDigits: 5 },
  { name: 'Chile', dialCode: '56', iso2: 'CL', maxPhoneDigits: 9 },
  { name: 'Cameroon', dialCode: '237', iso2: 'CM', maxPhoneDigits: 9 },
  { name: 'China', dialCode: '86', iso2: 'CN', maxPhoneDigits: 11 },
  { name: 'Colombia', dialCode: '57', iso2: 'CO', maxPhoneDigits: 10 },
  { name: 'Costa Rica', dialCode: '506', iso2: 'CR', maxPhoneDigits: 8 },
  { name: 'Cuba', dialCode: '53', iso2: 'CU', maxPhoneDigits: 8 },
  { name: 'Cape Verde', dialCode: '238', iso2: 'CV', maxPhoneDigits: 7 },
  { name: 'Curacao', dialCode: '599', iso2: 'CW', maxPhoneDigits: 7 },
  { name: 'Christmas Island', dialCode: '61', iso2: 'CX', maxPhoneDigits: 9 },
  { name: 'Cyprus', dialCode: '357', iso2: 'CY', maxPhoneDigits: 8 },
  { name: 'Czech Republic', dialCode: '420', iso2: 'CZ', maxPhoneDigits: 9 },
  { name: 'Germany', dialCode: '49', iso2: 'DE', maxPhoneDigits: 10 },
  { name: 'Djibouti', dialCode: '253', iso2: 'DJ', maxPhoneDigits: 10 },
  { name: 'Denmark', dialCode: '45', iso2: 'DK', maxPhoneDigits: 8 },
  { name: 'Dominica', dialCode: '1-767', iso2: 'DM', maxPhoneDigits: 10 },
  { name: 'Dominican Republic', dialCode: '1-809', iso2: 'DO', maxPhoneDigits: 10 },
  { name: 'Algeria', dialCode: '213', iso2: 'DZ', maxPhoneDigits: 9 },
  { name: 'Ecuador', dialCode: '593', iso2: 'EC', maxPhoneDigits: 9 },
  { name: 'Estonia', dialCode: '372', iso2: 'EE', maxPhoneDigits: 8 },
  { name: 'Egypt', dialCode: '20', iso2: 'EG', maxPhoneDigits: 10 },
  { name: 'Western Sahara', dialCode: '212', iso2: 'EH', maxPhoneDigits: 9 },
  { name: 'Eritrea', dialCode: '291', iso2: 'ER', maxPhoneDigits: 7 },
  { name: 'Spain', dialCode: '34', iso2: 'ES', maxPhoneDigits: 9 },
  { name: 'Ethiopia', dialCode: '251', iso2: 'ET', maxPhoneDigits: 9 },
  { name: 'Finland', dialCode: '358', iso2: 'FI', maxPhoneDigits: 11 },
  { name: 'Fiji', dialCode: '679', iso2: 'FJ', maxPhoneDigits: 7 },
  { name: 'Falkland Islands (Malvinas)', dialCode: '500', iso2: 'FK', maxPhoneDigits: 5 },
  { name: 'Micronesia, Federated States of', dialCode: '691', iso2: 'FM', maxPhoneDigits: 7 },
  { name: 'Faroe Islands', dialCode: '298', iso2: 'FO', maxPhoneDigits: 5 },
  { name: 'France', dialCode: '33', iso2: 'FR', maxPhoneDigits: 9 },
  { name: 'Gabon', dialCode: '241', iso2: 'GA', maxPhoneDigits: 7 },
  { name: 'United Kingdom', dialCode: '44', iso2: 'GB', maxPhoneDigits: 10 },
  { name: 'Grenada', dialCode: '1-473', iso2: 'GD', maxPhoneDigits: 10 },
  { name: 'Georgia', dialCode: '995', iso2: 'GE', maxPhoneDigits: 9 },
  { name: 'French Guiana', dialCode: '594', iso2: 'GF', maxPhoneDigits: 9 },
  { name: 'Guernsey', dialCode: '44', iso2: 'GG', maxPhoneDigits: 10 },
  { name: 'Ghana', dialCode: '233', iso2: 'GH', maxPhoneDigits: 9 },
  { name: 'Gibraltar', dialCode: '350', iso2: 'GI', maxPhoneDigits: 8 },
  { name: 'Greenland', dialCode: '299', iso2: 'GL', maxPhoneDigits: 6 },
  { name: 'Gambia', dialCode: '220', iso2: 'GM', maxPhoneDigits: 7 },
  { name: 'Guinea', dialCode: '224', iso2: 'GN', maxPhoneDigits: 9 },
  { name: 'Guadeloupe', dialCode: '590', iso2: 'GP', maxPhoneDigits: 9 },
  { name: 'Equatorial Guinea', dialCode: '240', iso2: 'GQ', maxPhoneDigits: 9 },
  { name: 'Greece', dialCode: '30', iso2: 'GR', maxPhoneDigits: 10 },
  { name: 'South Georgia and the South Sandwich Islands', dialCode: '500', iso2: 'GS', maxPhoneDigits: 5 },
  { name: 'Guatemala', dialCode: '502', iso2: 'GT', maxPhoneDigits: 8 },
  { name: 'Guam', dialCode: '1-671', iso2: 'GU', maxPhoneDigits: 10 },
  { name: 'Guinea-Bissau', dialCode: '245', iso2: 'GW', maxPhoneDigits: 9 },
  { name: 'Guyana', dialCode: '592', iso2: 'GY', maxPhoneDigits: 7 },
  { name: 'Hong Kong', dialCode: '852', iso2: 'HK', maxPhoneDigits: 8 },
  { name: 'Heard Island and McDonald Islands', dialCode: '672', iso2: 'HM', maxPhoneDigits: 10 },
  { name: 'Honduras', dialCode: '504', iso2: 'HN', maxPhoneDigits: 8 },
  { name: 'Croatia', dialCode: '385', iso2: 'HR', maxPhoneDigits: 9 },
  { name: 'Haiti', dialCode: '509', iso2: 'HT', maxPhoneDigits: 8 },
  { name: 'Hungary', dialCode: '36', iso2: 'HU', maxPhoneDigits: 9 },
  { name: 'Indonesia', dialCode: '62', iso2: 'ID', maxPhoneDigits: 11 },
  { name: 'Ireland', dialCode: '353', iso2: 'IE', maxPhoneDigits: 9 },
  { name: 'Israel', dialCode: '972', iso2: 'IL', maxPhoneDigits: 9 },
  { name: 'Isle of Man', dialCode: '44', iso2: 'IM', maxPhoneDigits: 10 },
  { name: 'India', dialCode: '91', iso2: 'IN', maxPhoneDigits: 10 },
  { name: 'British Indian Ocean Territory', dialCode: '246', iso2: 'IO', maxPhoneDigits: 7 },
  { name: 'Iraq', dialCode: '964', iso2: 'IQ', maxPhoneDigits: 10 },
  { name: 'Iran, Islamic Republic of', dialCode: '98', iso2: 'IR', maxPhoneDigits: 11 },
  { name: 'Iceland', dialCode: '354', iso2: 'IS', maxPhoneDigits: 7 },
  { name: 'Italy', dialCode: '39', iso2: 'IT', maxPhoneDigits: 10 },
  { name: 'Jersey', dialCode: '44', iso2: 'JE', maxPhoneDigits: 10 },
  { name: 'Jamaica', dialCode: '1-876', iso2: 'JM', maxPhoneDigits: 10 },
  { name: 'Jordan', dialCode: '962', iso2: 'JO', maxPhoneDigits: 9 },
  { name: 'Japan', dialCode: '81', iso2: 'JP' },
  { name: 'Kenya', dialCode: '254', iso2: 'KE', maxPhoneDigits: 10 },
  { name: 'Kyrgyzstan', dialCode: '996', iso2: 'KG', maxPhoneDigits: 9 },
  { name: 'Cambodia', dialCode: '855', iso2: 'KH', maxPhoneDigits: 9 },
  { name: 'Kiribati', dialCode: '686', iso2: 'KI', maxPhoneDigits: 8 },
  { name: 'Comoros', dialCode: '269', iso2: 'KM', maxPhoneDigits: 7 },
  { name: 'Saint Kitts and Nevis', dialCode: '1-869', iso2: 'KN', maxPhoneDigits: 10 },
  { name: "Korea, Democratic People's Republic of", dialCode: '850', iso2: 'KP', maxPhoneDigits: 13 },
  { name: 'Korea, Republic of', dialCode: '82', iso2: 'KR', maxPhoneDigits: 8 },
  { name: 'Kuwait', dialCode: '965', iso2: 'KW', maxPhoneDigits: 8 },
  { name: 'Cayman Islands', dialCode: '1-345', iso2: 'KY', maxPhoneDigits: 7 },
  { name: 'Kazakhstan', dialCode: '7', iso2: 'KZ', maxPhoneDigits: 10 },
  { name: "Lao People's Democratic Republic", dialCode: '856', iso2: 'LA', maxPhoneDigits: 9 },
  { name: 'Lebanon', dialCode: '961', iso2: 'LB', maxPhoneDigits: 8 },
  { name: 'Saint Lucia', dialCode: '1-758', iso2: 'LC', maxPhoneDigits: 7 },
  { name: 'Liechtenstein', dialCode: '423', iso2: 'LI', maxPhoneDigits: 7 },
  { name: 'Sri Lanka', dialCode: '94', iso2: 'LK', maxPhoneDigits: 7 },
  { name: 'Liberia', dialCode: '231', iso2: 'LR', maxPhoneDigits: 9 },
  { name: 'Lesotho', dialCode: '266', iso2: 'LS', maxPhoneDigits: 8 },
  { name: 'Lithuania', dialCode: '370', iso2: 'LT', maxPhoneDigits: 8 },
  { name: 'Luxembourg', dialCode: '352', iso2: 'LU', maxPhoneDigits: 9 },
  { name: 'Latvia', dialCode: '371', iso2: 'LV', maxPhoneDigits: 8 },
  { name: 'Libya', dialCode: '218', iso2: 'LY', maxPhoneDigits: 10 },
  { name: 'Morocco', dialCode: '212', iso2: 'MA', maxPhoneDigits: 9 },
  { name: 'Monaco', dialCode: '377', iso2: 'MC', maxPhoneDigits: 8 },
  { name: 'Moldova, Republic of', dialCode: '373', iso2: 'MD', maxPhoneDigits: 8 },
  { name: 'Montenegro', dialCode: '382', iso2: 'ME', maxPhoneDigits: 8 },
  { name: 'Saint Martin (French part)', dialCode: '590', iso2: 'MF', maxPhoneDigits: 6 },
  { name: 'Madagascar', dialCode: '261', iso2: 'MG', maxPhoneDigits: 7 },
  { name: 'Marshall Islands', dialCode: '692', iso2: 'MH', maxPhoneDigits: 7 },
  { name: 'Macedonia, the Former Yugoslav Republic of', dialCode: '389', iso2: 'MK', maxPhoneDigits: 8 },
  { name: 'Mali', dialCode: '223', iso2: 'ML', maxPhoneDigits: 8 },
  { name: 'Myanmar', dialCode: '95', iso2: 'MM', maxPhoneDigits: 10 },
  { name: 'Mongolia', dialCode: '976', iso2: 'MN', maxPhoneDigits: 8 },
  { name: 'Macao', dialCode: '853', iso2: 'MO', maxPhoneDigits: 8 },
  { name: 'Northern Mariana Islands', dialCode: '1-670', iso2: 'MP', maxPhoneDigits: 7 },
  { name: 'Martinique', dialCode: '596', iso2: 'MQ', maxPhoneDigits: 9 },
  { name: 'Mauritania', dialCode: '222', iso2: 'MR', maxPhoneDigits: 8 },
  { name: 'Montserrat', dialCode: '1-664', iso2: 'MS', maxPhoneDigits: 10 },
  { name: 'Malta', dialCode: '356', iso2: 'MT', maxPhoneDigits: 8 },
  { name: 'Mauritius', dialCode: '230', iso2: 'MU', maxPhoneDigits: 8 },
  { name: 'Maldives', dialCode: '960', iso2: 'MV', maxPhoneDigits: 7 },
  { name: 'Malawi', dialCode: '265', iso2: 'MW', maxPhoneDigits: 9 },
  { name: 'Mexico', dialCode: '52', iso2: 'MX', maxPhoneDigits: 10 },
  { name: 'Malaysia', dialCode: '60', iso2: 'MY', maxPhoneDigits: 7 },
  { name: 'Mozambique', dialCode: '258', iso2: 'MZ', maxPhoneDigits: 12 },
  { name: 'Namibia', dialCode: '264', iso2: 'NA', maxPhoneDigits: 7 },
  { name: 'New Caledonia', dialCode: '687', iso2: 'NC', maxPhoneDigits: 6 },
  { name: 'Niger', dialCode: '227', iso2: 'NE', maxPhoneDigits: 8 },
  { name: 'Norfolk Island', dialCode: '672', iso2: 'NF', maxPhoneDigits: 6 },
  { name: 'Nigeria', dialCode: '234', iso2: 'NG', maxPhoneDigits: 8 },
  { name: 'Nicaragua', dialCode: '505', iso2: 'NI', maxPhoneDigits: 8 },
  { name: 'Netherlands', dialCode: '31', iso2: 'NL', maxPhoneDigits: 9 },
  { name: 'Norway', dialCode: '47', iso2: 'NO', maxPhoneDigits: 8 },
  { name: 'Nepal', dialCode: '977', iso2: 'NP', maxPhoneDigits: 10 },
  { name: 'Nauru', dialCode: '674', iso2: 'NR', maxPhoneDigits: 7 },
  { name: 'Niue', dialCode: '683', iso2: 'NU', maxPhoneDigits: 4 },
  { name: 'New Zealand', dialCode: '64', iso2: 'NZ', maxPhoneDigits: 9 },
  { name: 'Oman', dialCode: '968', iso2: 'OM', maxPhoneDigits: 8 },
  { name: 'Panama', dialCode: '507', iso2: 'PA', maxPhoneDigits: 8 },
  { name: 'Peru', dialCode: '51', iso2: 'PE', maxPhoneDigits: 9 },
  { name: 'French Polynesia', dialCode: '689', iso2: 'PF', maxPhoneDigits: 8 },
  { name: 'Papua New Guinea', dialCode: '675', iso2: 'PG', maxPhoneDigits: 8 },
  { name: 'Philippines', dialCode: '63', iso2: 'PH', maxPhoneDigits: 10 },
  { name: 'Pakistan', dialCode: '92', iso2: 'PK', maxPhoneDigits: 10 },
  { name: 'Poland', dialCode: '48', iso2: 'PL', maxPhoneDigits: 9 },
  { name: 'Saint Pierre and Miquelon', dialCode: '508', iso2: 'PM', maxPhoneDigits: 6 },
  { name: 'Pitcairn', dialCode: '870', iso2: 'PN', maxPhoneDigits: 9 },
  { name: 'Puerto Rico', dialCode: '1', iso2: 'PR', maxPhoneDigits: 10 },
  { name: 'Palestine, State of', dialCode: '970', iso2: 'PS', maxPhoneDigits: 9 },
  { name: 'Portugal', dialCode: '351', iso2: 'PT', maxPhoneDigits: 9 },
  { name: 'Palau', dialCode: '680', iso2: 'PW', maxPhoneDigits: 7 },
  { name: 'Paraguay', dialCode: '595', iso2: 'PY', maxPhoneDigits: 9 },
  { name: 'Qatar', dialCode: '974', iso2: 'QA', maxPhoneDigits: 8 },
  { name: 'Reunion', dialCode: '262', iso2: 'RE', maxPhoneDigits: 10 },
  { name: 'Romania', dialCode: '40', iso2: 'RO', maxPhoneDigits: 10 },
  { name: 'Serbia', dialCode: '381', iso2: 'RS', maxPhoneDigits: 9 },
  { name: 'Russian Federation', dialCode: '7', iso2: 'RU', maxPhoneDigits: 10 },
  { name: 'Rwanda', dialCode: '250', iso2: 'RW', maxPhoneDigits: 9 },
  { name: 'Saudi Arabia', dialCode: '966', iso2: 'SA', maxPhoneDigits: 9 },
  { name: 'Solomon Islands', dialCode: '677', iso2: 'SB', maxPhoneDigits: 7 },
  { name: 'Seychelles', dialCode: '248', iso2: 'SC', maxPhoneDigits: 7 },
  { name: 'Sudan', dialCode: '249', iso2: 'SD', maxPhoneDigits: 7 },
  { name: 'Sweden', dialCode: '46', iso2: 'SE', maxPhoneDigits: 7 },
  { name: 'Singapore', dialCode: '65', iso2: 'SG', maxPhoneDigits: 8 },
  { name: 'Saint Helena', dialCode: '290', iso2: 'SH', maxPhoneDigits: 4 },
  { name: 'Slovenia', dialCode: '386', iso2: 'SI', maxPhoneDigits: 9 },
  { name: 'Svalbard and Jan Mayen', dialCode: '47', iso2: 'SJ', maxPhoneDigits: 8 },
  { name: 'Slovakia', dialCode: '421', iso2: 'SK', maxPhoneDigits: 9 },
  { name: 'Sierra Leone', dialCode: '232', iso2: 'SL', maxPhoneDigits: 8 },
  { name: 'San Marino', dialCode: '378', iso2: 'SM', maxPhoneDigits: 10 },
  { name: 'Senegal', dialCode: '221', iso2: 'SN', maxPhoneDigits: 9 },
  { name: 'Somalia', dialCode: '252', iso2: 'SO', maxPhoneDigits: 9 },
  { name: 'Suriname', dialCode: '597', iso2: 'SR', maxPhoneDigits: 7 },
  { name: 'South Sudan', dialCode: '211', iso2: 'SS', maxPhoneDigits: 7 },
  { name: 'Sao Tome and Principe', dialCode: '239', iso2: 'ST', maxPhoneDigits: 7 },
  { name: 'El Salvador', dialCode: '503', iso2: 'SV', maxPhoneDigits: 8 },
  { name: 'Sint Maarten (Dutch part)', dialCode: '1-721', iso2: 'SX', maxPhoneDigits: 10 },
  { name: 'Syrian Arab Republic', dialCode: '963', iso2: 'SY', maxPhoneDigits: 7 },
  { name: 'Swaziland', dialCode: '268', iso2: 'SZ', maxPhoneDigits: 8 },
  { name: 'Turks and Caicos Islands', dialCode: '1-649', iso2: 'TC', maxPhoneDigits: 10 },
  { name: 'Chad', dialCode: '235', iso2: 'TD', maxPhoneDigits: 6 },
  { name: 'French Southern Territories', dialCode: '262', iso2: 'TF', maxPhoneDigits: 10 },
  { name: 'Togo', dialCode: '228', iso2: 'TG', maxPhoneDigits: 8 },
  { name: 'Thailand', dialCode: '66', iso2: 'TH', maxPhoneDigits: 9 },
  { name: 'Tajikistan', dialCode: '992', iso2: 'TJ', maxPhoneDigits: 9 },
  { name: 'Tokelau', dialCode: '690', iso2: 'TK', maxPhoneDigits: 5 },
  { name: 'Timor-Leste', dialCode: '670', iso2: 'TL', maxPhoneDigits: 7 },
  { name: 'Turkmenistan', dialCode: '993', iso2: 'TM', maxPhoneDigits: 8 },
  { name: 'Tunisia', dialCode: '216', iso2: 'TN', maxPhoneDigits: 8 },
  { name: 'Tonga', dialCode: '676', iso2: 'TO', maxPhoneDigits: 5 },
  { name: 'Turkey', dialCode: '90', iso2: 'TR', maxPhoneDigits: 11 },
  { name: 'Trinidad and Tobago', dialCode: '1-868', iso2: 'TT', maxPhoneDigits: 7 },
  { name: 'Tuvalu', dialCode: '688', iso2: 'TV', maxPhoneDigits: 5 },
  { name: 'Taiwan, Province of China', dialCode: '886', iso2: 'TW', maxPhoneDigits: 9 },
  { name: 'United Republic of Tanzania', dialCode: '255', iso2: 'TZ', maxPhoneDigits: 7 },
  { name: 'Ukraine', dialCode: '380', iso2: 'UA', maxPhoneDigits: 9 },
  { name: 'Uganda', dialCode: '256', iso2: 'UG', maxPhoneDigits: 7 },
  { name: 'United States', dialCode: '1', iso2: 'US', maxPhoneDigits: 10 },
  { name: 'Uruguay', dialCode: '598', iso2: 'UY', maxPhoneDigits: 8 },
  { name: 'Uzbekistan', dialCode: '998', iso2: 'UZ', maxPhoneDigits: 9 },
  { name: 'Holy See (Vatican City State)', dialCode: '379', iso2: 'VA', maxPhoneDigits: 10 },
  { name: 'Saint Vincent and the Grenadines', dialCode: '1-784', iso2: 'VC', maxPhoneDigits: 7 },
  { name: 'Venezuela', dialCode: '58', iso2: 'VE', maxPhoneDigits: 7 },
  { name: 'British Virgin Islands', dialCode: '1-284', iso2: 'VG', maxPhoneDigits: 7 },
  { name: 'US Virgin Islands', dialCode: '1-340', iso2: 'VI', maxPhoneDigits: 10 },
  { name: 'Vietnam', dialCode: '84', iso2: 'VN', maxPhoneDigits: 9 },
  { name: 'Vanuatu', dialCode: '678', iso2: 'VU', maxPhoneDigits: 5 },
  { name: 'Wallis and Futuna', dialCode: '681', iso2: 'WF', maxPhoneDigits: 6 },
  { name: 'Samoa', dialCode: '685', iso2: 'WS', maxPhoneDigits: 7 },
  { name: 'Kosovo', dialCode: '383', iso2: 'XK', maxPhoneDigits: 8 },
  { name: 'Yemen', dialCode: '967', iso2: 'YE', maxPhoneDigits: 9 },
  { name: 'Mayotte', dialCode: '262', iso2: 'YT', maxPhoneDigits: 9 },
  { name: 'South Africa', dialCode: '27', iso2: 'ZA', maxPhoneDigits: 9 },
  { name: 'Zambia', dialCode: '260', iso2: 'ZM', maxPhoneDigits: 9 },
  { name: 'Zimbabwe', dialCode: '263', iso2: 'ZW', maxPhoneDigits: 9 },
];

// Looked up by dialCode (matches the stored/selected dial code exactly, same
// key already used at every phone-field call site) — used to cap how many
// digits a phone input accepts for the currently selected country.
// Multiple countries can share a dialCode (e.g. NANP's plain "1"); the
// first match is used, which is fine since NANP countries all share the
// same 10-digit national length anyway.
export function getMaxPhoneDigits(dialCode: string): number | undefined {
  return COUNTRIES.find((c) => c.dialCode === dialCode)?.maxPhoneDigits;
}
