// App-specific role enum — previously generated by Prisma from schema.prisma;
// now hand-defined since the schema lives in supabase/migrations/0001_init.sql
// (see the matching Postgres enum `public.app_role`).
export type Role = 'super_admin' | 'verification_staff' | 'agent' | 'buyer' | 'owner';
